export const items = [
    {
        id: 0,
        author: "Suzana Marie",
        avatar: "/images/avatar-6.jpg",
        content:
            "Artiik Analysis shows that clients who receive weekly updates are 40% more likely to engage with new features.",
        image: "/images/slider-pic-1.png",
    },
    {
        id: 1,
        author: "Tyson Martine",
        avatar: "/images/avatar-2.png",
        content:
            "Insights generated by Artiik indicate Users from urban regions tend to spend 25% more time on the app than those from rural areas.",
        image: "/images/slider-pic-1.png",
    },
    {
        id: 2,
        author: "Terrence Jaskolski",
        avatar: "/images/avatar-3.jpg",
        content:
            "This AI Agent showed that products recommended based on prior purchases have a 30% higher conversion rate.",
        image: "/images/slider-pic-1.png",
    },
    {
        id: 3,
        author: "Dani Roberson",
        avatar: "/images/avatar-4.jpg",
        content:
            "I found that targeted campaigns on social media result in 30% more click-throughs than generic ads, thanks to Artiik AI.",
        image: "/images/slider-pic-1.png",
    },
];
